<a href="https://colab.research.google.com/github/melinalessa/Machine_Learning/blob/main/exe4_labelencoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Em relação ao arquivo notas.csv:
Realize o tratamento categórico usando a técnica LabelEncoder
para a coluna EVENTO MAIS RECENTE, RAZÃO SOCIAL EMITENTE e
UF_EMITENTE.
Quantas categorizações é possível obter em cada uma dessas
colunas?

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/LyndainesSantos/Machine-Learning/main/tratamento_dados/Exercicios/notas.csv")

<ipython-input-2-56c26033a8ac>:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("https://raw.githubusercontent.com/LyndainesSantos/Machine-Learning/main/tratamento_dados/Exercicios/notas.csv")


In [3]:
df.head(20)

Unnamed: 0 CHAVE DE ACESSO  \
0            0     4,22301E+43   
1            1     4,22301E+43   
2            2     3,32301E+43   
3            3     4,22301E+43   
4            4     5,12301E+43   
5            5     3,52301E+43   
6            6     3,52301E+43   
7            7     3,52301E+43   
8            8     3,52301E+43   
9            9     3,32301E+43   
10          10     3,32301E+43   
11          11     3,52301E+43   
12          12     3,32301E+43   
13          13     4,32301E+43   
14          14     4,32301E+43   
15          15     4,32301E+43   
16          16     5,12301E+43   
17          17     5,32302E+43   
18          18     5,32302E+43   
19          19     3,32301E+43   

                                               MODELO  SÉRIE    NÚMERO  \
0   55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...    3.0  755441.0   
1   55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...    3.0  755428.0   
2   55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...    1.0      16.0   
3                                                 NaN    3.0  755891.0   
4   55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...    4.0    2393.0   
5   55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...    1.0     170.0   
6   55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...    1.0     173.0   
7   55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...    1.0     180.0   
8   55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...    1.0     181.0   
9   55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...    1.0   59443.0   
10  55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...    1.0   59444.0   
11  55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...    1.0     315.0   
12  55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...    1.0   59445.0   
13  55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...    1.0    6888.0   
14  55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...    1.0    6889.0   
15  55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...    1.0    6890.0   
16  55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...    1.0   29177.0   
17  55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...    0.0  152190.0   
18  55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...    0.0  152188.0   
19  55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...    1.0      15.0   

                                 NATUREZA DA OPERAÇÃO      DATA EMISSÃO  \
0          Outra saida merc./prest.serv. nao especif.  01/01/2023 04:01   
1   Remessa de bem p/conta contrato de comodato ou...  01/01/2023 04:08   
2          VENDA DE MARCADORIA ADQUIRIDA DE TERCEIROS               NaN   
3          Outra saida merc./prest.serv. nao especif.               NaN   
4                   109264 - VENDA / COMBUST. LUBRIF.               NaN   
5                                               VENDA               NaN   
6                                               VENDA               NaN   
7                                               VENDA               NaN   
8                                               VENDA               NaN   
9                      OUTRA SAIDA , NAO ESPECIFICADA               NaN   
10                      OUTRA SAIDA, NAO ESPECIFICADA               NaN   
11                                              VENDA               NaN   
12                     OUTRA SAIDA , NAO ESPECIFICADA               NaN   
13                                VENDA DE MERCADORIA               NaN   
14                                VENDA DE MERCADORIA               NaN   
15                                VENDA DE MERCADORIA               NaN   
16                                VENDA DE MERCADORIA               NaN   
17          Prestacao de servico tributado pelo ISSQN               NaN   
18          Prestacao de servico tributado pelo ISSQN               NaN   
19         VENDA DE MARCADORIA ADQUIRIDA DE TERCEIROS               NaN   

                                  EVENTO MAIS RECENTE  \
0                                  Autorização de Uso   
1                                  Autorizaç

In [4]:
# Econder
encoder = LabelEncoder()

In [5]:
# Categorizar
evento_recente = encoder.fit_transform(df['EVENTO MAIS RECENTE'])

In [11]:
evento_recente

array([0, 0, 0, ..., 0, 0, 0])

In [6]:
# Valores únicos
np.unique(evento_recente)

array([0, 1, 2, 3, 4, 5, 6])

In [7]:
razao_social = encoder.fit_transform(df['RAZÃO SOCIAL EMITENTE'])

In [12]:
razao_social

array([13153, 13153, 12936, ..., 11322, 13594,  3781])

In [8]:
np.unique(razao_social).shape

(14917,)

In [9]:
uf = encoder.fit_transform(df['UF EMITENTE'])

In [13]:
uf

array([23, 23, 18, ..., 10, 25, 22])

In [10]:
np.unique(uf).shape

(27,)